const mail = require('../handlers/mail');
const fs = require('fs');
const promisify = require('es6-promisify');
const path = require('path');

exports.aboutPage = (req, res) => {
  res.render('generic', {
    title: 'About Us',
      content: `<p>CBDOilMaps is an online community where CBD oil enthusiasts can connect with users and businesses in their area to review and discuss local CBD oil dispensaries and their products. Listing is completely free for both businesses and customers. Premium advertising is available, if desired.</p>`
  });
};

exports.privacyPage = (req, res) => {
    res.render('generic', {
        title: 'Privacy Policy',
        content: `<p>This privacy policy discloses the privacy practices for CBDOILMAPS.COM. This privacy policy applies solely to information collected by this domain. It will notify you of the following:</p>
                   <ol><li>What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.</li>
                  <li>What choices are available to you regarding the use of your data.</li>
                  <li>The security procedures in place to protect the misuse of your information.</li>
                  <li>How you can correct any inaccuracies in the information.</li>
                  </ol>
                  <p><b>Information Collection, Use, and Sharing</b><br />
                   We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.
                   We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order, or to provide our products and services.
                  Applying for a Merchant Account: If you apply for a merchant account from or through CBDOILMAPS.COM, CBDOILMAPS.COM may use and disclose the Information to evaluate your eligibility for a merchant account, including disclosure to consumer reporting agencies, relevant financial institutions, and other entities involved in providing the merchant account services. CBDOILMAPS.COM may also use and disclose your Information during the course of providing or obtaining on your behalf the merchant account services.
                   Furthermore, CBDOILMAPS.COM generally collects information for the following purposes:</p>
                  <ul>
                   <li>To engage in transactions and communications. Personally-identifiable information such as name, address, e-mail, purchase details, and credit card/payment information may be collected and stored as a necessary part of transactions and its attendant history. CBDOILMAPS.COM may need to share some of this information with fulfillment houses, credit card/check clearing houses, and other similarly-situated third parties as a requirement to complete a transaction.</li>
                  <li>To provide service and support.</li>
                  <li>User inquiries and requests for information.</li>
                  <li>To provide useful marketing information. We may use contact information from you to provide timely and relevant notices of corporate events, product releases, updates, and service developments.</li>
                  <li>To authenticate your identity.</li>
                  <li>To comply with applicable law and law enforcement authorities.</li>
                  </ul>
                  <p>
                   Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.
                   Access
                   CBDOILMAPS.COM will provide you with reasonable access to your Personal Information that we hold and will undertake reasonable steps to enable your correction, amendment, or deletion of information demonstrated to be inaccurate or incomplete.
                   Security
                   CBDOILMAPS.COM will take reasonable precautions to ensure your Personal Information is protected from loss, misuse, and unauthorized access, disclosure, alteration, and destruction.
                   Links
                   This web site contains links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally identifiable information.
                   Cookies
                   We use “cookies” on this site. A cookie is a piece of data stored on a site visitor’s hard drive to help us improve your access to our site and identify repeat visitors to our site. For instance, when we use a cookie to identify you, you would not have to log in a password more than once, thereby saving time while on our site. Cookies can also enable us to track and target the interests of our users to enhance the experience on our site. Usage of a cookie is in no way linked to any personally identifiable information on our site.
                   Sharing
                   We partner with another party to provide specific services. When the user signs up for these services, we will share names, or other contact information that is necessary for the third party to provide these services. These parties are not allowed to use personally identifiable information except for the purpose of providing these services.
                   Updates
                   Our Privacy Policy may change from time to time and all updates will be posted on this page. In addition, any changes to our privacy policy will be emailed to site members.</p> 
                  `
    });
};

exports.termsPage = (req, res) => {
    res.render('generic', {
        title: 'Terms & Conditions',
        content: `The websites located at www.cbdoilmaps.com , 
                  (the “Sites”) are copyrighted work belonging to BMJ Group, Inc. DBA www.cbdoilmps.com and www.iprocesscbdoil.com and www.iprocessmarijuana.com.  The Site provides resources related to CBD Oil (Cannabinoid), and other Hemp products and related products which include reviews and ratings provided by its users, directories of CBD Oil websites and retail CBD Oil locations and CBD Oil and cannabis-related news stories and other articles; and offers certain products for sale (collectively, with all other services provided through the Site, the “Services”). Certain features of the Services or Site may be subject to additional guidelines, terms, or rules, which will be posted on the Service or Site in connection with such features. All such additional terms, guidelines, and rules are incorporated by reference into this Agreement.
                  
                  THESE TERMS OF USE (“AGREEMENT”) SETS FORTH THE LEGALLY BINDING TERMS FOR YOUR USE OF THE SITE AND SERVICES. BY ACCESSING OR USING THE SITE OR SERVICES, YOU ARE ACCEPTING THIS AGREEMENT AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THIS AGREEMENT. YOU MAY NOT ACCESS OR USE THE SITE OR SERVICES OR ACCEPT THE AGREEMENT IF YOU DO NOT HAVE THE CAPACITY TO ENTER INTO THIS AGREEMENT. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THIS AGREEMENT, DO NOT ACCESS AND/OR USE THE SITE OR SERVICES. IF YOU ARE USING THE SITE OR SERVICES ON BEHALF OF A COMPANY, ENTITY, OR ORGANIZATION, YOU REPRESENT AND WARRANT THAT YOU ARE AN AUTHORIZED REPRESENTATIVE OF SUCH COMPANY, ENTITY, OR ORGANIZATION WITH THE AUTHORITY TO BIND IT TO THIS AGREEMENT. YOU MUST ALSO BE 18 YEARS OR 21 YEARS OF AGE TO ENTER THIS WEBSITE, DEPENDING UPON YOUR JURISDICTION.
                  1. IMPORTANT DISCLAIMERS. ALL INFORMATION CONTAINED ON THE SITE AND SERVICES IS FOR INFORMATIONAL PURPOSES ONLY. CONTENT POSTED BY CBDOILMAPS.COM ON ANY WEBSITE, MOBILE APPLICATION, SOCIAL MEDIA CHANNEL, THIRD-PARTY CONTENT SERVICE, OR ADVERTISEMENT IS FOR INFORMATIONAL PURPOSES ONLY. CBDOILMAPS.COM DOES NOT ENDORSE, AND IS NOT RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF, ANY OPINION, ADVICE, STATEMENT, OR OTHER INFORMATION MADE ON THE SITE OR SERVICES, INCLUDING USER CONTENT AND THIRD PARTY MATERIALS (EACH AS DEFINED BELOW). CBDOILMAPS.COM IS NOT RESPONSIBLE FOR YOUR RELATIONSHIP WITH ANY WEBSITE, DISPENSARY, RETAIL LOCATION, HEALTH CARE PROVIDER, OR OTHER USERS OF THE SITE OR SERVICES. CBDOILMAPS.COM IS NOT OBLIGATED TO SCREEN WEBSITES, DISPENSARIES, RETAIL LOCATIONS, HEALTH CARE PROVIDERS, OR THEIR MENUS TO DETERMINE WHETHER THEY ARE QUALIFIED OR AUTHORIZED BY LAW TO PROVIDE THEIR SERVICES OR TO DETERMINE THE ACCURACY OF THEIR MENUS OR OTHER INFORMATION THEY PROVIDE.
                  CBDOILMAPS.COM DOES NOT OFFER MEDICAL ADVICE. ANY INFORMATION ACCESSED THROUGH THE SITE AND SERVICES, OR WITHIN ANY OF CBDOILMAPS.COM’S SOCIAL MEDIA PAGES OR CHANNELS IS FOR INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY, IT IS NOT INTENDED TO BE A SUBSITUTE FOR MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT, AND IS NOT INTENDED TO COVER ALL POSSIBLE USES, DIRECTIONS, PRECAUTIONS, OR ADVERSE EFFECTS. SUCH INFORMATION INCLUDES WITHOUT LIMITATION, THIRD PARTY MATERIALS, USER CONTENT AND CBDOILMAPS.COM-GENERATED CONTENT DERIVED FROM USER CONTENT (E.G., STRAIN HIGHLIGHTS, ATTRIBUTES, AND OTHER DATA). THE INFORMATION ON THE SITE AND SERVICES AND PROVIDED VIA CBDOILMAPS.COM’S SOCIAL MEDIA PAGES AND CHANNELS SHOULD NOT BE USED FOR THE DIAGNOSIS OR TREATMENT OF ANY MEDICAL CONDITION. ALWAYS CONSULT YOUR DOCTOR OR OTHER QUALIFIED HEALTH CARE PROVIDER IF YOU HAVE ANY QUESTIONS ABOUT A MEDICAL CONDITION. NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE OR DELAY IN SEEKING IT BECAUSE OF SOMETHING YOU HAVE READ ON THE SITE, SERVICES, OR ON CBDOILMAPS.COM’S SOCIAL MEDIA PAGES AND CHANNELS.
                  THE FOREGOING DISCLAIMERS AND LIMITATIONS ON LIABILITY SHALL NOT LIMIT THE MORE GENERAL DISCLAIMERS AND LIMITATIONS ON LIABILITY IN SECTIONS 8 AND 9 OR ELSEWHERE IN THIS AGREEMENT. CBDOIL
                  FDA DISCLAIMER- tHE STATEMENTS MADE REGARDING THE PRODUCTS on the CBDOILMAPS.COM WEBSITE HAVE NOT BEEN EVALUATED BY THE FOOD AND DRUG ADMINISTRATION. THE EFFICACY OF THESE PRODUCTS HAS NOT BEEN CONFIRMED BY FDA APPROVED RESEARCH. THESE PRODUCTS ARE NOT INTENDEDTO DIAGNOSE, TREAT, CURE OR PREVENT ANY DISEASE. ALL INFORMATION PRESENTED here is not meant as a substitute for or alternative to information from health care practitioners. PLEASE CONSULT YOUR HEALTH CARE PROFESSIONALS ABOUT POTENTIAL INTERACTIONS OR OTHER POSSIBLE COMPLICATIONS BEFORE USING ANY PRODUCT. THE FEDERAL FOOD, DRUG AND COSMETIC ACT REQUIRES THIS NOTICE.
                   2. Accounts
                  2.1 Account Creation.In order to use certain features of the Site (e.g., to use the Services), you must register for an account with CBDoilmaps.com (“CBDoilmaps.com  Account”) and provide certain information about yourself as prompted by the Site registration form. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; and (b) you will maintain the accuracy of such information. You may not create more than one CBDoilmaps.com Account. You may delete your CBDoilmaps.com Account at any time, for any reason, by following the instructions on the Site. CBDoilmaps.com may suspend or terminate your CBDoilmaps.com Account in accordance with Section 10.
                  2.2 Account Responsibilities. You are responsible for maintaining the confidentiality of your CBDoilmaps.com Account login information and are fully responsible for all activities that occur under your CBDoilmaps.com Account. You agree to immediately notify CBDoilmaps.com of any unauthorized use, or suspected unauthorized use of your CBDoilmaps.com Account or any other breach of security. CBDoilmaps.com cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.
                  2.3 Social Networking Services. Alternatively, we may permit you to login to the Site or Service or otherwise associate your CBDoilmaps.com Account with your login credentials from certain social networking sites (e.g., Facebook) (“SNS”). If you log in or otherwise associate your CBDoilmaps.com Account with your login credentials from a SNS, we may receive information about you from such SNS, in accordance with the terms and conditions (e.g., terms of use and privacy policy) of the SNS (“SNS Terms”). If you elect to share your information with these SNS, we will share information with them in accordance with your election. The SNS Terms of these SNS will apply to the information we disclose to them.
                  3. SITE AND MOBILE APP
                  3.1 License. Subject to the terms of this Agreement, CBDoilmaps.com grants you a non-transferable, non-exclusive, license to use the Site and Services for your personal, noncommercial use. Subject to the terms of this Agreement, CBDoilmaps.com grants you a non-transferable, non-exclusive, license to install and use the software CBDoilmaps.com makes available for mobile devices (“Mobile App”), in executable object code format only, solely on your own handheld mobile device and for your personal, noncommercial use. As used in this Agreement, the term “Services” includes the Mobile App.
                  3.2 Certain Restrictions. The rights granted to you in this Agreement are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site or Services; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site or Services; (c) you shall not access the Site or Services in order to build a similar or competitive service; and (d) except as expressly stated herein, no part of the Site or Services may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Any future release, update, or other addition to functionality of the Site or Services shall be subject to the terms of this Agreement. All copyright and other proprietary notices on any Site or Services content must be retained on all copies thereof.
                  3.3 Modification. CBDoilmaps.com reserves the right, at any time, to modify, suspend, or discontinue the Site or Services or any part thereof with or without notice. You agree that CBDoilmaps.com will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Site or Services or any part thereof.
                  3.4 Ownership. Excluding your User Content (defined below), you acknowledge that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Site and Services are owned by CBDoilmaps.com or CBDoilmaps.com’s licensors. The provision of the Site and Services does not transfer to you or any third party any rights, title or interest in or to such intellectual property rights. CBDoilmaps.com and its suppliers reserve all rights not granted in this Agreement.
                  3.5 App Platforms. You acknowledge and agree that the availability of the Mobile App is dependent on the third party app platform from which you received the Mobile App, e.g., the Apple App Store® (“App Platform”). You acknowledge that this Agreement is between you and CBDoilmaps.com and not with the App Platform. CBDoilmaps.com, not the App Platform, is solely responsible for the App, the content thereof, maintenance, support services, and warranty therefor, and addressing any claims relating thereto (e.g., product liability, legal compliance, or intellectual property infringement). You agree to pay all fees charged by the App Platform in connection with the Mobile App. Each App Platform may have its own terms and conditions to which you must agree before downloading the Mobile App from it. You agree to comply with, and your license to use the Mobile App is conditioned upon your compliance with, all applicable agreements, terms and conditions of use/service, and other policies of the applicable App Platform. You acknowledge that the App Platform (and its subsidiaries) is a third party beneficiary of this Agreement and will have the right to enforce this Agreement.  See Accessing and Downloading the Application from Apple® in Section 12.5 below for additional terms and conditions if you access or download the Mobile App from the Apple App Store.
                  4. USER CONTENT
                  4.1 User Content. “User Content” means any and all information and content that a user submits to, or uses with, the Site or Services, including without limitation, content in the user’s profile, user reviews and/or postings. You acknowledge and agree that CBDoilmaps.com is not responsible for any User Content, including its accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. CBDoilmaps.com does not assume and will not have any liability or responsibility to you or any other person or user for your use or misuse of any User Content. 
                  4.2 User Content – Your Responsibilities. You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that makes you or any third party personally identifiable. You hereby represent and warrant that your User Content does not violate the Acceptable Use Policy (defined below). You may not state or imply that your User Content is in any way provided, sponsored or endorsed by CBDoilmaps.com. Because you alone are responsible for your User Content (and not CBDoilmaps.com), you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy. CBDoilmaps.com is not obligated to backup any User Content and User Content may be deleted at any time. You are solely responsible for creating backup copies of your User Content if you desire.
                  4.2 License. You hereby grant, and you represent and warrant that you have the right to grant, to CBDoilmaps.com an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use your User Content, and to grant sublicenses of the foregoing, solely for the purposes of including your User Content in the Site and Services. You agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content.
                  4.3 Feedback. If you provide CBDoilmaps.com any feedback or suggestions regarding the Site or Services (“Feedback”), you hereby assign to CBDoilmaps.com all rights in the Feedback and agree that CBDoilmaps.com shall have the right to use such Feedback and related information in any manner it deems appropriate. CBDoilmaps.com will treat any Feedback you provide to CBDoilmaps.com as non-confidential and non-proprietary. You agree that you will not submit to CBDoilmaps.com any information or ideas that you consider to be confidential or proprietary.
                  5. ACCEPTABLE USE POLICY. The following sets forth CBDoilmaps.com’s “Acceptable Use Policy”:
                  5.1 General Restrictions. You agree not to use the Site, Services, or any of CBDoilmaps.com's social media pages or channels to collect, upload, transmit, display, or distribute any User Content (a) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (b) that is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive (e.g., material that promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual) or otherwise objectionable material of any kind or nature or which is harmful to minors in any way; or (c) in violation of any law, regulation, or obligations or restrictions imposed by any third party.
                  5.2 Reviews. You agree not to post reviews on the Site, Services, or any of CBDoilmaps.com’s social media pages or channels that are not based upon your personal experience or are otherwise designed for any purpose other than providing other users on the Site with an accurate description of your personal experience. Reviews based on secondhand, non-personal experience are not allowed. In addition to the other restrictions contained in the Acceptable Use Policy, reviews posted on the Site, Services, or any of CBDoilmaps.com’s social media pages or channels must not: (a) be written exclusively in capital letters, (b) be plagiarized, (c) contain spam or advertisements, (d) contain personally identifying information about any Dispensary employees or any other person, (e) contain overly detailed or sexual descriptions of an individual’s physical appearance, or lewd personal attacks against a specific individual or group of individuals affiliated with the Dispensary, (f) contain references to Dispensaries or competitors other than the product or Dispensary being reviewed, or (g) contain unrelated personal grievances. If you are an owner, volunteer, or employee of a Dispensary you may not post reviews about your Dispensary or products or about your competitors’ Dispensary or products.
                  5.3 Photos. Image files must exclusively feature the products they illustrate and must not include body parts, messy or cluttered backgrounds, product wrapping, currency, paraphernalia, brand names, or other any objects other than the product itself. Image files must be clear and must not be blurry, fuzzy, or contain any flash reflections. Products should be centered in the image file. Image files must contain an accurate depiction of the product they illustrate. Image files cannot contain pornography or other graphic images and must otherwise abide by the guidelines set forth in this Section 5.
                  5.4 Technological Restrictions. In addition, you agree not to use the Site or Services to: (a) upload, transmit, or distribute any computer viruses, worms, or any software intended to damage or alter a computer system or data; (b) send unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (c) harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (d) interfere with, disrupt, or create an undue burden on servers or networks connected to the Site or Services or violate the regulations, policies or procedures of such networks; (e) attempt to or impersonate another user or CBDoilmaps.com or gain unauthorized access to the Site or Services, other computer systems or networks connected to or used together with the Site or Services, through password mining or other means; (f) harass or interfere with another user’s use and enjoyment of the Site or Services; or (g) introduce software or automated agents or scripts to the Site or Services so as to produce multiple accounts, generate automated searches, requests and queries, or to strip, scrape, or mine data from the Site or Services.
                  5.5 Monitoring, Suspension, and Termination. We reserve the right (but have no obligation) to review any User Content (including any image files or reviews), investigate, and/or take appropriate action against you in our sole discretion (including removing or modifying your User Content, terminating your CBDoilmaps.com Account in accordance with Section 10, and/or reporting you to law enforcement authorities) if we in our sole discretion suspect that you have violated the Acceptable Use Policy or any other provision of this Agreement or otherwise create liability for us or any other person.
                  6. INDEMNITY. You agree to indemnify and hold CBDoilmaps.com (and its officers, employees, and agents) harmless from any and all losses, damages, liabilities, claims, actions, judgments, awards, penalties, fines, costs and expenses (including reasonably attorneys’ fees) arising from or relating to any claim or demand made by any third party due to or arising out of (i) your use or misuse of the Site or Services, (ii) your User Content, (iii) your violation of this Agreement; or (iv) your violation of applicable laws or regulations. CBDoilmaps.com reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of CBDoilmaps.com. CBDoilmaps.com will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.
                  7. THIRD PARTY MATERIALS; DEALS; OTHER USERS; RELEASE
                  7.1 Third Party Materials. The Site or Services might display, include or make available third-party content (including data, information, articles applications or other products, services and/or materials) or contain links to third party websites, services, and advertisements for third parties such as Deals (defined below) (collectively, “Third Party Materials”). You acknowledge and agree that CBDoilmaps.com is not responsible for Third Party Materials, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. CBDoilmaps.com does not assume and will not have any liability or responsibility to you or any other person or user for any Third Party Materials. Third Party Materials and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk. When you link to a Third Party Material, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third Party Material.
                  7.2 Deals. The Site or Services might display, include or make available coupons, promotional codes, giveaways, samples, and other offers from listed dispensaries (collectively, “Deals”). Deals constitute “Third Party Materials” under this Agreement. CBDoilmaps.com displays these Deals on the Site and Services as a form of advertisement for the listing dispensary (the “Offeror”) only. All Deals are offered directly by the applicable Offeror, and may be subject to additional terms, conditions, or restrictions of the Offeror or under applicable law, whether or not such additional terms, conditions or restrictions are expressly included on the Site or Services. The Offeror, and not CBDoilmaps.com, is solely responsible for: (a) redemption of the Deal; (b) compliance of all aspects of the Deal with applicable law (including without limit, the advertisement, redemption, and terms, conditions and restrictions related thereto); (c) all goods and services it provides to you in connection with the Deal; and (d) all injuries, illnesses, damages, claims, liabilities and costs it may cause you to suffer, directly or indirectly, in full or in part, whether related to the use or redemption of a Deal or not.
                  7.3 Other Users. Each user of the Site or Services is solely responsible for any and all of its User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content and we make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content, and we assume no responsibility for any User Content. Your interactions with other Site or Service users (including Dispensaries) are solely between you and such user. You agree that CBDoilmaps.com will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Site or Service user, we are under no obligation to become involved.
                  7.4 Release.You hereby release and forever discharge CBDoilmaps.com (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish your rights with respect to, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or relates directly or indirectly to, any interactions with, or act or omission of, other Site or Service users or Third Party Materials. IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.”
                  
                  8. DISCLAIMERS
                  THE SITE AND SERVICES ARE PROVIDED “AS-IS” AND “AS AVAILABLE” AND WE (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, CBDOILMAPS.COM (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE SITE OR SERVICES: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE.
                  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.
                  9. LIMITATION ON LIABILITY
                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL CBDOILMAPS.COM (AND OUR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT OR YOUR USE OF, OR INABILITY TO USE, THE SITE OR SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SITE AND SERVICES ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING THEREFROM. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, CBDOILMAPS.COM’S (AND OUR SUPPLIERS’) LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU’VE PAID CBDOILMAPS.COM IN THE PRIOR 12 MONTHS (IF ANY). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT.
                  SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU AND YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.
                  10. TERM AND TERMINATION. Subject to this Section, this Agreement will remain in full force and effect while you use the Site or Services. We may (a) suspend your rights to use the Site and/or Services (including your CBDoilmaps.com Account) or (b) terminate this Agreement, at any time for any reason at our sole discretion, including for any use of the Site or Services in violation of this Agreement. Upon termination of this Agreement, your CBDoilmaps.com Account and right to access and use the Site and Services will terminate immediately. You understand that any termination of your CBDoilmaps.com Account involves deletion of your User Content associated therewith from our Site, Services, and live databases. CBDoilmaps.com will not have any liability whatsoever to you for any termination of this Agreement, including for termination of your CBDoilmaps.com Account or deletion of your User Content. Even after this Agreement is terminated, the following provisions of this Agreement will remain in effect: Sections 3.2-3.4, 4–12.
                  11. COPYRIGHT POLICY. CBDoilmaps.com respects the intellectual property of others and asks that users of our Site and Services do the same. In connection with our Site and Services, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination, in appropriate circumstances, of users of our Site and Services who are repeat infringers of intellectual property rights, including copyrights. If you believe that one of our users is, through the use of our Site and Services, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to 17 U.S.C. § 512(c)) must be provided to our designated Copyright Agent:
                  11.1 your physical or electronic signature;
                  11.2 identification of the copyrighted work(s) that you claim to have been infringed;
                  11.3 identification of the material on our services that you claim is infringing and that you request us to remove;
                  11.4 sufficient information to permit us to locate such material;
                  11.5 your address, telephone number, and e-mail address;
                  11.6 a statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and
                  11.7 a statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner.
                  Please note that, pursuant to 17 U.S.C. § 512(f), any misrepresentation of material fact (falsities) in a written notification automatically subjects the complaining party to liability for any damages, costs and attorney’s fees incurred by us in connection with the written notification and allegation of copyright infringement.
                  The Designated Copyright Agent for CBDoilmaps.com is: Copyright Agent
                  12. GENERAL
                  12.1 No Support or Maintenance. You acknowledge and agree that CBDoilmaps.com will have no obligation to provide you with any support or maintenance in connection with the Site or Services.
                  12.2 Changes to Terms of Use. This Agreement is subject to occasional revision, and if we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any) and/or by prominently posting notice of the changes on our Site. Any changes to this Agreement will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on our Site. These changes will be effective immediately for new users of our Site or Services. You are responsible for providing us with your most current e-mail address. In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice. Continued use of our Site or Services following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.
                  12.3 ARBITRATION AGREEMENT AND JURY TRIAL WAIVER, CLASS ACTION WAIVER, AND FORUM SELECTION CLAUSE. Except for disputes brought in small claims court, all disputes between you and CBDoilmaps.com arising out of, relating to or in connection with the Site or Services shall be exclusively settled through binding arbitration pursuant to the then-current rules of the American Arbitration Association (“AAA”) for commercial arbitration. There is no judge or jury in arbitration. Arbitration procedures are simpler and more limited than rules applicable in court and review by a court is limited. YOU AND CBDOILMAPS.COM AGREE THAT ANY SUCH ARBITRATION SHALL BE CONDUCTED ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION. Notwithstanding any provision in this Agreement to the contrary, if the class-action waiver in the prior sentence is deemed invalid or unenforceable, however, neither you nor we are entitled to arbitration. This arbitration agreement is subject to the Federal Arbitration Act. The arbitrator’s award may be entered in any court of competent jurisdiction. Notwithstanding any provision in this Agreement to the contrary, we agree that if CBDoilmaps.com makes any future change to this dispute resolution provision, it will not apply to any individual claim(s) that you had already provided notice of to CBDoilmaps.com. Information on AAA and how to start arbitration can be found at www.adr.org or by calling 800-778-7879. If the arbitration in this section provision is found unenforceable or to not apply for a given dispute, then the proceeding must be brought exclusively in a court of competent jurisdiction in Bucks County, Pennsylvania. You hereby accept the exclusive jurisdiction of such court for this purpose. This Agreement is governed by the laws of the State of Pennsylvania without regard to conflict of law provisions.
                  12.4 Copyright/Trademark Information. Copyright © 2017, BMJ Group,  Inc. All rights reserved. CBDoilmaps.com®; the CBDoilmaps.com logo; the CBDoilmaps.com colors used in combination; the CBDoilmaps.com slogan; and the CBDoilmaps.com website designs (collectively, the “Marks”) are trademarks of CBDoilmaps.com, Apple®, App Store®, and iTunes Store® are trademarks of Apple Inc. (“Apple”).  You acknowledge and agree that You are not permitted to use CBDoilmaps.com’s Marks or any third party marks displayed on our site without prior written consent from, respectively, CBDoilmaps.com Holdings, Inc., Apple, or the owners of such third party marks. 
                  12.5 Accessing and Downloading the Application from Apple. The following additional terms apply to any Mobile App accessed through or downloaded from the iTunes Store® or the App Store (“App Store Sourced Mobile App”):
                  (a) You acknowledge and agree that (i) this Agreement is concluded between you and CBDoilmaps.com only, and not Apple, and (ii) that CBDoilmaps.com, not Apple, is solely responsible for the App Store Sourced Mobile App and content thereof. The license granted to you in the Agreement to use the App Store Sourced Mobile App and Service is a non-transferable right to use the App Store Sourced Mobile App on any Apple Device that you own or control, and only as permitted by the Usage Rules set forth in the App Store Terms of Service.
                  (b) You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store Sourced Mobile App.
                  (c) In the event of any failure of the App Store Sourced Mobile App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App Store Sourced Mobile App to you.  To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App Store Sourced Mobile App. As between CBDoilmaps.com and Apple, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of CBDoilmaps.com.
                  (d) You and CBDoilmaps.com acknowledge that, as between CBDoilmaps.com and Apple, Apple is not responsible for addressing any claims you have or any claims of any third-party relating to the App Store Sourced Mobile App or your possession and use of the App Store Sourced Mobile App, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store Sourced Mobile App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.
                  (e) You and CBDoilmaps.com acknowledge that, in the event of any third-party claim that the App Store Sourced Mobile App or your possession and use of that App Store Sourced Mobile App infringes that third-party’s intellectual property rights, as between CBDoilmaps.com and Apple, CBDoilmaps.com, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by the Terms.
                  (f) You and CBDoilmaps.com acknowledge and agree that Apple, and Apple’s subsidiaries, are third-party beneficiaries of the Agreement as related to your license of the App Store Sourced Mobile App, and that, upon your acceptance of the terms and conditions of the Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce the Agreement as related to your license of the App Store Sourced Mobile App against you as a third-party beneficiary thereof.
                  (g) You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.
                  (h) Without limiting any other terms of the Terms, you must comply with all applicable third-party terms of agreement when using the App Store Sourced Mobile App.
                  12.6 Miscellaneous. This Agreement constitutes the entire agreement between you and us regarding the use of the Site and Services. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision, nor shall any single or partial exercise by CBDoilmaps.com of any right or power hereunder preclude further exercise of that or any other right hereunder. The section titles in this Agreement are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation”. If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Nothing contained herein shall be construed to establish an employment, partnership, or joint venture relationship between you and CBDoilmaps.com. This Agreement, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without CBDoilmaps.com’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The terms of this Agreement shall be binding upon assignees.
                  12.7 CBDoilmaps.com Contact Information: 
                  
                  CBDOILMAPS.COM
                  207 E PENNSYLVANIA BLVD
                  LOWER LEVEL OFFICE
                  Feasterville, PA. 19053
                  
                  ATTN: MW`
    });
};

exports.contactPage = async (req, res) => {
    if (req.body.email) {
        const contact = {
            name: req.body.name,
            email: req.body.email,
            message: req.body.message
        };
        const cbd = {email: 'mikeW@cbdoilmaps.com'};
        await mail.send({
            user: contact,
            filename: 'contact-form',
            subject: 'Contact form sent',
            contact
        });
        await mail.send({
            user: cbd,
            filename: 'contact-form',
            subject: 'Contact form sent',
            contact
        });
        req.flash('success', 'Contact form sent from: ' + contact.email);
        return res.redirect('back');
    }
    res.render('contact', { title: 'Contact' });
};

exports.sitemap = (req, res) => {
    res.sendFile(path.join(__dirname, '../sitemap.xml'));
};